---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру.
  - Пользователь должен иметь возможность просматривать товары и просматривать информацию о товаре.
non-functional:
  - Сайт должен быть доступен доступен по всему миру и быть готовым к использованию не более чем за 1 секунду.
  - Сайт должен иметь мобильную версию, которая открывается на ТОП-5 браузерах.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать миллион посетителей в сутки.
  - Сайт должен выдерживать пиковые нагрузки до 100 000 посетителей в час.
  - Сайт должен быть доступен на мобильных устройствах.
  - Должна быть возможность наращивать кол-во фильтров по мере роста каталога
implicit:
  - Эксплуатация сайта должна соответствовать требованиям законодательства РФ.
  - Пользователь должен иметь возможность создать уникальный "Личный кабинет" с последующей аутентификацией.
  - На сайте должна быть предусмотрена возможность обратной связи с технической поддержкой магазина.
  - Пользователь должен иметь возможность удалять товары из корзины.
  - Сайт должен предоставлять актуальную информацию о наличии товаров на складе.
  - Иллюстрация и описание товара должна соответствовать действительности.
